### ISSUE TITLE
cannot load such file -- ffi (LoadError)

### ISSUE THREAD

**Issue by vtrtbbs** [enkessler/childprocess#181] opened 2022-02-21 13:06 UTC
I have FFI installed, version 1.15.5, which appears when I run > rake test

The following error occurs:

`E:\blog\blog>rake test
d:/Ruby30/lib/ruby/gems/3.0.0/gems/childprocess-4.1.0/lib/childprocess/windows.rb:6:in `rescue in <main>': FFI is a required pre-requisite for Windows or posix_spawn support in the ChildProcess gem. Ensure the `ffi` gem is installed. If you believe this is an error, please file a bug at http://github.com/enkessler/childprocess/issues (ChildProcess::MissingFFIError)
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/childprocess-4.1.0/lib/childprocess/windows.rb:3:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/childprocess-4.1.0/lib/childprocess.rb:209:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:20:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium-webdriver.rb:20:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `each'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `each'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler.rb:176:in `require'
        from E:/blog/blog/config/application.rb:7:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
        from E:/blog/blog/config/environment.rb:2:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
        from E:/blog/blog/test/test_helper.rb:2:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from E:/blog/blog/test/channels/application_cable/connection_test.rb:1:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:47:in `each'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:47:in `load_tests'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:40:in `run'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands/test/test_command.rb:33:in `perform'        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/command/base.rb:87:in `perform'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/command.rb:48:in `invoke'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- ffi (LoadError)
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/childprocess-4.1.0/lib/childprocess/windows.rb:4:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/childprocess-4.1.0/lib/childprocess.rb:209:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:20:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium-webdriver.rb:20:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `each'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `each'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `require'
        from d:/Ruby30/lib/ruby/site_ruby/3.0.0/bundler.rb:176:in `require'
        from E:/blog/blog/config/application.rb:7:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
        from E:/blog/blog/config/environment.rb:2:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
        from E:/blog/blog/test/test_helper.rb:2:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from E:/blog/blog/test/channels/application_cable/connection_test.rb:1:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:47:in `block in load_tests'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:47:in `each'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:47:in `load_tests'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/test_unit/runner.rb:40:in `run'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands/test/test_command.rb:33:in `perform'        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/command/base.rb:87:in `perform'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/command.rb:48:in `invoke'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from d:/Ruby30/lib/ruby/gems/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
`

**Comment by enkessler** [comment] 2022-02-24 17:21
Duplicate of #180

**Comment by sds** [comment] 2024-01-07 06:47
`childprocess` will no longer use/require `ffi` as of version 5.x, which was just released.

**Closed by sds** 2024-01-07 06:47 UTC
